# Generated by Django 4.2.2 on 2023-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QoeRating',
            fields=[
                ('qoe_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('qoe_rating_value', models.IntegerField()),
            ],
            options={
                'db_table': 'qoe_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QoeVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=45)),
                ('packet_loss_value', models.FloatField()),
                ('rtt_value', models.FloatField()),
                ('network', models.CharField(max_length=45)),
                ('video_file_path', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'qoe_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationVideo',
            fields=[
                ('validation_video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('validation_video_name', models.CharField(max_length=45)),
                ('validation_video_file_path', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'validation_video',
                'managed': False,
            },
        ),
    ]
